/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-10-28 17:08:27 UTC)
 * on 2014-11-07 at 04:33:41 UTC 
 * Modify at your own risk.
 */

package com.googleappengine.emergencyreadybackend.entity.policelineendpoint.model;

/**
 * Model definition for PoliceLine.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the policelineendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PoliceLine extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String contactNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String stationCity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long stationId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String stationName;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getContactNumber() {
    return contactNumber;
  }

  /**
   * @param contactNumber contactNumber or {@code null} for none
   */
  public PoliceLine setContactNumber(java.lang.String contactNumber) {
    this.contactNumber = contactNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStationCity() {
    return stationCity;
  }

  /**
   * @param stationCity stationCity or {@code null} for none
   */
  public PoliceLine setStationCity(java.lang.String stationCity) {
    this.stationCity = stationCity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getStationId() {
    return stationId;
  }

  /**
   * @param stationId stationId or {@code null} for none
   */
  public PoliceLine setStationId(java.lang.Long stationId) {
    this.stationId = stationId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStationName() {
    return stationName;
  }

  /**
   * @param stationName stationName or {@code null} for none
   */
  public PoliceLine setStationName(java.lang.String stationName) {
    this.stationName = stationName;
    return this;
  }

  @Override
  public PoliceLine set(String fieldName, Object value) {
    return (PoliceLine) super.set(fieldName, value);
  }

  @Override
  public PoliceLine clone() {
    return (PoliceLine) super.clone();
  }

}
