/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-10-28 17:08:27 UTC)
 * on 2014-11-15 at 06:31:01 UTC 
 * Modify at your own risk.
 */

package com.newemergencyreadybackend.entity.emergencyservicesendpoint.model;

/**
 * Model definition for EmergencyServices.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the emergencyservicesendpoint. For a detailed explanation
 * see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class EmergencyServices extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String contactNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String stationCategory;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String stationCity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String stationLatitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String stationLongitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String stationName;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getContactNumber() {
    return contactNumber;
  }

  /**
   * @param contactNumber contactNumber or {@code null} for none
   */
  public EmergencyServices setContactNumber(java.lang.String contactNumber) {
    this.contactNumber = contactNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public EmergencyServices setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStationCategory() {
    return stationCategory;
  }

  /**
   * @param stationCategory stationCategory or {@code null} for none
   */
  public EmergencyServices setStationCategory(java.lang.String stationCategory) {
    this.stationCategory = stationCategory;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStationCity() {
    return stationCity;
  }

  /**
   * @param stationCity stationCity or {@code null} for none
   */
  public EmergencyServices setStationCity(java.lang.String stationCity) {
    this.stationCity = stationCity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStationLatitude() {
    return stationLatitude;
  }

  /**
   * @param stationLatitude stationLatitude or {@code null} for none
   */
  public EmergencyServices setStationLatitude(java.lang.String stationLatitude) {
    this.stationLatitude = stationLatitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStationLongitude() {
    return stationLongitude;
  }

  /**
   * @param stationLongitude stationLongitude or {@code null} for none
   */
  public EmergencyServices setStationLongitude(java.lang.String stationLongitude) {
    this.stationLongitude = stationLongitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStationName() {
    return stationName;
  }

  /**
   * @param stationName stationName or {@code null} for none
   */
  public EmergencyServices setStationName(java.lang.String stationName) {
    this.stationName = stationName;
    return this;
  }

  @Override
  public EmergencyServices set(String fieldName, Object value) {
    return (EmergencyServices) super.set(fieldName, value);
  }

  @Override
  public EmergencyServices clone() {
    return (EmergencyServices) super.clone();
  }

}
